name: Delete old workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
      # At 6 AM everyday

jobs:
  delete-docs:
    permissions: write-all
    uses: ./.github/workflows/delete.yml
  coronation:
    runs-on: thevickypedia-lite
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
