name: Delete Docs Branch

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  delete-docs-branch:
    runs-on: thevickypedia-default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Delete 'docs' branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git show-ref --verify --quiet refs/heads/docs; then
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/git/refs/heads/docs
          else
            echo "Branch 'docs' does not exist."
          fi
        shell: bash
